name: Deploy to production environment


on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
            cd fastapi-book-project
            echo "Current directory: $(pwd)"
            echo "Git remote configuration:"
            git remote -v
            echo "Fetching updates..."
            git fetch origin
            echo "Pulling from main branch..."
            git pull origin main || { echo "git pull failed"; exit 1; }
            echo "Installing requirements..."
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi_app
            sudo systemctl restart nginx
          EOF

      - name: Notify Telex - Deployment Successful
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "event_name": "cd_pipeline",
            "username": "GitHub Actions",
            "status": "success",
            "message": "✅ Deployment successful for commit ${{ github.sha }}."
          }' "https://ping.telex.im/v1/webhooks/01950b90-b1bf-75b7-b9e6-e831fdd18b5f"

      - name: Notify Telex - Deployment Failed
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "event_name": "cd_pipeline",
            "username": "GitHub Actions",
            "status": "failure",
            "message": "❌ Deployment failed for commit ${{ github.sha }}."
          }' "https://ping.telex.im/v1/webhooks/01950b90-b1bf-75b7-b9e6-e831fdd18b5f"    