name: CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash  # Ensures compatibility across OS

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash

    - name: Test with pytest
      run: |
        pytest
      shell: bash

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
            cd fastapi-book-project
            echo "Current directory: $(pwd)"
            echo "Git remote configuration:"
            git remote -v
            echo "Fetching updates..."
            git fetch origin
            echo "Pulling from main branch..."
            git pull origin main || { echo "git pull failed"; exit 1; }
            echo "Installing requirements..."
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi_app
            sudo systemctl restart nginx
          EOF